'''
Question: Create a program that will play the “cows and bulls” game with the user. The game works like this:
Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout the game and tell the user at the end.
Say the number generated by the computer is 1038. An example interaction could look like this:
  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
Until the user guesses the number.
'''

def cows_and_bulls(random_input):
    print(random_input)
    random_number = [i for i in str(random_input)]
    guesses = 0
    while(1):
        cows = 0
        bulls = 0
        user_input = (input())
        user_number = [i for i in user_input]
        for i,j in zip(user_number,random_number):
            if user_number == random_number:
                guesses += 1
                return f"{user_input} is correct!\nYou guessed the correct number in {guesses} tries."
            elif i in random_number and i==j:
                cows+=1
            elif i in random_number and not i==j:
                bulls+=1
            else:
                continue
        guesses+=1
        print(f"{cows} cows, {bulls} bulls")

import random as r
random_input = r.choice(range(1000,10000))
print(cows_and_bulls(random_input))
        
        

        